spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/learn
spring.datasource.username=postgres
spring.datasource.password=p@$$word
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
