spring.application.name=demo

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.url=jdbc:postgresql://localhost:5432/learn
spring.datasource.username=postgres
spring.datasource.password=p@$$word
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.path=/api-docs
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

file.upload-dir=./uploads
